const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const LOCATIONS = [
  {
    slug: 'aryabhatta',
    name: 'Aryabhatta',
    category: 'Hostel',
    latitude: 24.7554,
    longitude: 92.7845,
    mapsUrl: 'https://maps.google.com/?q=24.7554,92.7845',
    description: 'Aryabhatta Hostel',
    isActive: true,
  },
  {
    slug: 'nit-silchar-main-campus',
    name: 'National Institute of Technology, Silchar (Main Campus)',
    category: 'Institute / Landmark',
    latitude: 24.758555,
    longitude: 92.7944703,
    mapsUrl: 'https://www.google.com/maps?q=24.758555,92.7944703',
    description: 'Overall institute point on Google Maps; central reference point for the campus.',
    isActive: true,
  },
  {
    slug: 'nit-silchar-main-gate',
    name: 'NIT Silchar Main Gate',
    category: 'Gate',
    latitude: 24.7584728,
    longitude: 92.796043,
    mapsUrl: 'https://www.google.com/maps?q=24.7584728,92.796043',
    description: "Primary entry/exit gate of the campus, listed as 'NIT GATE' on Google Maps.",
    isActive: true,
  },
  {
    slug: 'new-administrative-building',
    name: 'New Administrative Building',
    category: 'Administrative',
    latitude: 24.7585474,
    longitude: 92.7943734,
    mapsUrl: 'https://www.google.com/maps?q=24.7585474,92.7943734',
    description: "Main administrative block housing the Registrar's office and central administration; newly constructed high-tech building.",
    isActive: true,
  },
  {
    slug: 'apj-abdul-kalam-central-library',
    name: 'Bharat Ratna Dr. A.P.J. Abdul Kalam Learning Resource Centre (Central Library)',
    category: 'Library',
    latitude: 24.757377,
    longitude: 92.7892895,
    mapsUrl: 'https://www.google.com/maps?q=24.757377,92.7892895',
    description: 'Central Library of the institute, one of the largest in Asia; part of the LRC/LTT building.',
    isActive: true,
  },
  {
    slug: 'central-computer-center',
    name: 'Central Computer Center',
    category: 'Academic / Facility',
    latitude: 24.757041,
    longitude: 92.7901846,
    mapsUrl: 'https://www.google.com/maps?q=24.757041,92.7901846',
    description: '24-hour computer center used for computing facilities, competitive exams, and general student computing needs.',
    isActive: true,
  },
  {
    slug: 'dept-electrical-engineering',
    name: 'Department of Electrical Engineering',
    category: 'Academic Department',
    latitude: 24.7571801,
    longitude: 92.7924391,
    mapsUrl: 'https://www.google.com/maps?q=24.7571801,92.7924391',
    description: 'Houses EE classrooms, faculty offices, and labs.',
    isActive: true,
  },
  {
    slug: 'dept-eie',
    name: 'Department of Electronics and Instrumentation Engineering (EIE)',
    category: 'Academic Department',
    latitude: 24.7565124,
    longitude: 92.7895433,
    mapsUrl: 'https://www.google.com/maps?q=24.7565124,92.7895433',
    description: 'Houses EIE classrooms, faculty offices, and labs.',
    isActive: true,
  },
  {
    slug: 'dept-civil-engineering',
    name: 'Department of Civil Engineering',
    category: 'Academic Department',
    latitude: 24.756249,
    longitude: 92.792876,
    mapsUrl: 'https://www.google.com/maps?q=24.756249,92.792876',
    description: 'One of the oldest departments (est. 1977), with multiple testing/research labs.',
    isActive: true,
  },
  {
    slug: 'dept-mechanical-engineering',
    name: 'Department of Mechanical Engineering',
    category: 'Academic Department',
    latitude: 24.7585303,
    longitude: 92.7919962,
    mapsUrl: 'https://www.google.com/maps?q=24.7585303,92.7919962',
    description: 'One of the oldest departments; houses workshops and material science labs.',
    isActive: true,
  },
  {
    slug: 'dept-chemistry',
    name: 'Department of Chemistry',
    category: 'Academic Department',
    latitude: 24.7574105,
    longitude: 92.7924937,
    mapsUrl: 'https://www.google.com/maps?q=24.7574105,92.7924937',
    description: 'Chemistry classrooms and research labs.',
    isActive: true,
  },
  {
    slug: 'dept-management-studies',
    name: 'Department of Management Studies',
    category: 'Academic Department',
    latitude: 24.7573974,
    longitude: 92.7914095,
    mapsUrl: 'https://www.google.com/maps?q=24.7573974,92.7914095',
    description: 'Houses the MBA program and related classrooms/offices.',
    isActive: true,
  },
  {
    slug: 'nit-canteen',
    name: 'NIT Canteen',
    category: 'Food / Canteen',
    latitude: 24.7587331,
    longitude: 92.7944172,
    mapsUrl: 'https://www.google.com/maps?q=24.7587331,92.7944172',
    description: 'Main student canteen inside campus.',
    isActive: true,
  },
  {
    slug: 'nits-cafe',
    name: "NIT's Cafe",
    category: 'Food / Cafe',
    latitude: 24.7583921,
    longitude: 92.792625,
    mapsUrl: 'https://www.google.com/maps?q=24.7583921,92.792625',
    description: 'Popular on-campus cafe for snacks, quick bites, and small celebrations; only dedicated cafe on campus.',
    isActive: true,
  },
  {
    slug: 'nit-silchar-guest-house',
    name: 'NIT Silchar Guest House',
    category: 'Guest House',
    latitude: 24.7568799,
    longitude: 92.7945081,
    mapsUrl: 'https://www.google.com/maps?q=24.7568799,92.7945081',
    description: 'Institute guest house for visiting faculty, parents, and official guests.',
    isActive: true,
  },
  {
    slug: 'sports-complex-main-auditorium',
    name: 'Sports Complex (Main Auditorium/Hall)',
    category: 'Auditorium / Sports',
    latitude: 24.7559242,
    longitude: 92.7833424,
    mapsUrl: 'https://www.google.com/maps?q=24.7559242,92.7833424',
    description: "Largest indoor hall in campus (~2000 capacity); used for concerts, fests, ramp walks, freshers' and farewell parties.",
    isActive: true,
  },
  {
    slug: 'indoor-stadium',
    name: 'Indoor Stadium',
    category: 'Sports Facility',
    latitude: 24.7567253,
    longitude: 92.7887438,
    mapsUrl: 'https://www.google.com/maps?q=24.7567253,92.7887438',
    description: 'Indoor sports facility used for kho-kho, chess, and other indoor tournaments.',
    isActive: true,
  },
  {
    slug: 'football-ground-nit-silchar',
    name: 'Football Ground, NIT Silchar',
    category: 'Sports Facility',
    latitude: 24.7574748,
    longitude: 92.7831399,
    mapsUrl: 'https://www.google.com/maps?q=24.7574748,92.7831399',
    description: 'Main football/athletic ground; also used for Independence/Republic Day events and exhibitions during fests.',
    isActive: true,
  },
  {
    slug: 'student-activity-centre-sac',
    name: 'Student Activity Centre (SAC)',
    category: 'Student Activity Centre',
    latitude: 24.756611,
    longitude: 92.7888751,
    mapsUrl: 'https://www.google.com/maps?q=24.756611,92.7888751',
    description: 'Recreation hub for students — badminton, table tennis, carrom, chess; also used for blood donation camps and events.',
    isActive: true,
  },
  {
    slug: 'nit-silchar-post-office',
    name: 'NIT Silchar Post Office',
    category: 'Administrative / Postal',
    latitude: 24.7565751,
    longitude: 92.7944394,
    mapsUrl: 'https://www.google.com/maps?q=24.7565751,92.7944394',
    description: 'On-campus post office serving students, faculty and staff (part of India Post).',
    isActive: true,
  },
  {
    slug: 'silchar-medical-college-hospital',
    name: 'Silchar Medical College and Hospital (SMCH)',
    category: 'Health / Hospital',
    latitude: 24.7758006,
    longitude: 92.794962,
    mapsUrl: 'https://www.google.com/maps?q=24.7758006,92.794962',
    description: 'Nearest major government hospital used for serious medical emergencies; located just outside campus on Masimpur-Silchar road.',
    isActive: true,
  },
  // ── Hostels ──────────────────────────────────────────────────────────────
  {
    slug: 'bh8a',
    name: 'BH8A',
    category: 'Hostel',
    latitude: 24.7587983,
    longitude: 92.7886192,
    mapsUrl: 'https://maps.google.com/?q=24.7587983,92.7886192',
    description: 'Boys Hostel 8A',
    isActive: true,
  },
  {
    slug: 'bh8b',
    name: 'BH8B',
    category: 'Hostel',
    latitude: 24.7584136,
    longitude: 92.7884400,
    mapsUrl: 'https://maps.google.com/?q=24.7584136,92.7884400',
    description: 'Boys Hostel 8B',
    isActive: true,
  },
  {
    slug: 'bh8c',
    name: 'BH8C',
    category: 'Hostel',
    latitude: 24.7590133,
    longitude: 92.7882079,
    mapsUrl: 'https://maps.google.com/?q=24.7590133,92.7882079',
    description: 'Boys Hostel 8C',
    isActive: true,
  },
  {
    slug: 'bh8d',
    name: 'BH8D',
    category: 'Hostel',
    latitude: 24.7596503,
    longitude: 92.7861181,
    mapsUrl: 'https://maps.google.com/?q=24.7596503,92.7861181',
    description: 'Boys Hostel 8D',
    isActive: true,
  },
  {
    slug: 'aryabhatta-hostel',
    name: 'Aryabhatta Hostel / ABH',
    category: 'Hostel',
    latitude: 24.7554,
    longitude: 92.7845,
    mapsUrl: 'https://maps.google.com/?q=24.7554,92.7845',
    description: 'Aryabhatta Hostel (ABH)',
    isActive: true,
  },
  {
    slug: 'bh1',
    name: 'BH1 (Bh 1)',
    category: 'Hostel',
    latitude: 24.7577316,
    longitude: 92.7864524,
    mapsUrl: 'https://maps.google.com/?q=24.7577316,92.7864524',
    description: 'Boys Hostel 1',
    isActive: true,
  },
  {
    slug: 'bh2',
    name: 'BH2 (Bh 2)',
    category: 'Hostel',
    latitude: 24.7578918,
    longitude: 92.7875702,
    mapsUrl: 'https://maps.google.com/?q=24.7578918,92.7875702',
    description: 'Boys Hostel 2',
    isActive: true,
  },
  {
    slug: 'bh3',
    name: 'BH3 (Bh 3)',
    category: 'Hostel',
    latitude: 24.7579738,
    longitude: 92.7881266,
    mapsUrl: 'https://maps.google.com/?q=24.7579738,92.7881266',
    description: 'Boys Hostel 3',
    isActive: true,
  },
  {
    slug: 'bh4',
    name: 'BH4 (Bh 4)',
    category: 'Hostel',
    latitude: 24.7578470,
    longitude: 92.7878410,
    mapsUrl: 'https://maps.google.com/?q=24.7578470,92.7878410',
    description: 'Boys Hostel 4',
    isActive: true,
  },
  {
    slug: 'bh6-bh7',
    name: 'BH6 (Bh 6) and BH7 (Bh 7)',
    category: 'Hostel',
    latitude: 24.7582791,
    longitude: 92.7863761,
    mapsUrl: 'https://maps.google.com/?q=24.7582791,92.7863761',
    description: 'Boys Hostel 6 and 7',
    isActive: true,
  },
  {
    slug: 'bh8',
    name: 'BH8 (Bh 8)',
    category: 'Hostel',
    latitude: 24.7592448,
    longitude: 92.7880763,
    mapsUrl: 'https://maps.google.com/?q=24.7592448,92.7880763',
    description: 'Boys Hostel 8',
    isActive: true,
  },
  // ── Girls Hostels ─────────────────────────────────────────────────────────
  {
    slug: 'gh1',
    name: 'GH1 (Gh 1)',
    category: 'Hostel',
    latitude: 24.7546970,
    longitude: 92.7803264,
    mapsUrl: 'https://maps.google.com/?q=24.7546970,92.7803264',
    description: 'Girls Hostel 1',
    isActive: true,
  },
  {
    slug: 'gh2',
    name: 'GH2 (Gh 2)',
    category: 'Hostel',
    latitude: 24.7546070,
    longitude: 92.7803261,
    mapsUrl: 'https://maps.google.com/?q=24.7546070,92.7803261',
    description: 'Girls Hostel 2',
    isActive: true,
  },
  {
    slug: 'gh3',
    name: 'GH3 (Gh 3)',
    category: 'Hostel',
    latitude: 24.7554908,
    longitude: 92.7815309,
    mapsUrl: 'https://maps.google.com/?q=24.7554908,92.7815309',
    description: 'Girls Hostel 3',
    isActive: true,
  },
  {
    slug: 'gh4',
    name: 'GH4',
    category: 'Hostel',
    latitude: 24.7498985,
    longitude: 92.7800425,
    mapsUrl: 'https://maps.google.com/?q=24.7498985,92.7800425',
    description: 'Girls Hostel 4',
    isActive: true,
  },
  // ── Food / Hangout Spots ──────────────────────────────────────────────────
  {
    slug: 'tea-garden',
    name: 'Tea Garden',
    category: 'Food / Cafe',
    latitude: 24.7570601,
    longitude: 92.7809681,
    mapsUrl: 'https://maps.google.com/?q=24.7570601,92.7809681',
    description: 'Popular tea stall and hangout spot on campus.',
    isActive: true,
  },
  {
    slug: 'fps',
    name: 'FPS',
    category: 'Food / Canteen',
    latitude: 24.7586609,
    longitude: 92.7999585,
    mapsUrl: 'https://maps.google.com/?q=24.7586609,92.7999585',
    description: 'FPS – Food Plaza / Snack Point near hostels.',
    isActive: true,
  },
  {
    slug: 'james-corner-sbi-pnb-startup',
    name: 'James Corner, SBI and PNB, StartUp',
    category: 'Food / Canteen',
    latitude: 24.7580507,
    longitude: 92.7884273,
    mapsUrl: 'https://maps.google.com/?q=24.7580507,92.7884273',
    description: 'James Corner food stall area with SBI and PNB ATMs and startup space nearby.',
    isActive: true,
  },
  {
    slug: 't-point',
    name: 'T Point',
    category: 'Food / Canteen',
    latitude: 24.7570504,
    longitude: 92.7901895,
    mapsUrl: 'https://maps.google.com/?q=24.7570504,92.7901895',
    description: 'T Point – popular junction/tea point for students.',
    isActive: true,
  },
  // ── Academic / Research Facilities ───────────────────────────────────────
  {
    slug: 'cdac',
    name: 'CDAC',
    category: 'Academic / Facility',
    latitude: 24.7584410,
    longitude: 92.7909185,
    mapsUrl: 'https://maps.google.com/?q=24.7584410,92.7909185',
    description: 'Centre for Development of Advanced Computing (CDAC) on campus.',
    isActive: true,
  },
  {
    slug: 'new-gallery-dept-management-studies',
    name: 'New Gallery / Department of Management Studies',
    category: 'Academic Department',
    latitude: 24.7581006,
    longitude: 92.7903994,
    mapsUrl: 'https://maps.app.goo.gl/76cR6ow5xomJ5Yk8g',
    description: 'New Gallery and Department of Management Studies building.',
    isActive: true,
  },
  {
    slug: 'kv-school',
    name: 'KV School',
    category: 'Academic / Facility',
    latitude: 24.7512624,
    longitude: 92.7891735,
    mapsUrl: 'https://maps.app.goo.gl/fRtcTlwenfcqv7GA7g',
    description: 'Kendriya Vidyalaya School located within or near the NIT campus.',
    isActive: true,
  },
  {
    slug: 'doms',
    name: 'DOMS',
    category: 'Academic Department',
    latitude: 24.7573694,
    longitude: 92.7914095,
    mapsUrl: 'https://maps.app.goo.gl/pA8CeKZ9HHRx2XS277g',
    description: 'Department of Management Studies (DOMS).',
    isActive: true,
  },
  {
    slug: 'food-court',
    name: 'Food Court',
    category: 'Food / Canteen',
    latitude: 24.7573974,
    longitude: 92.7914095,
    mapsUrl: 'https://maps.app.goo.gl/HvNs7a1V8mrgRFA',
    description: 'Main food court area on campus.',
    isActive: true,
  },
  {
    slug: 'dispensary',
    name: 'Dispensary',
    category: 'Health / Hospital',
    latitude: 24.7573974,
    longitude: 92.7914095,
    mapsUrl: 'https://maps.app.goo.gl/pA8CeKZ9HHRx2XS277g',
    description: 'Campus dispensary for basic medical needs.',
    isActive: true,
  },
  {
    slug: 'marriage-scholar-hostel',
    name: 'Marriage Scholar Hostel',
    category: 'Hostel',
    latitude: 24.7573974,
    longitude: 92.7914095,
    mapsUrl: 'https://maps.app.goo.gl/sqwQlMbADM8mzKinZ89',
    description: 'Hostel for married scholars/research scholars on campus.',
    isActive: true,
  },
  {
    slug: 'innovation-lab',
    name: 'Innovation Lab',
    category: 'Academic / Facility',
    latitude: 24.7578385,
    longitude: 92.7825842,
    mapsUrl: 'https://maps.app.goo.gl/hXD2D0PFf27H7R7g',
    description: 'Innovation and entrepreneurship lab on campus.',
    isActive: true,
  },
  {
    slug: 'earthquake-building',
    name: 'Earthquake Building',
    category: 'Academic / Facility',
    latitude: 24.7557696,
    longitude: 92.7826095,
    mapsUrl: 'https://maps.app.goo.gl/mQKoGJr8XKTefT27A',
    description: 'Earthquake engineering research building / shake table lab.',
    isActive: true,
  },
  {
    slug: 'mechanical-workshop',
    name: 'Mechanical Workshop',
    category: 'Academic Department',
    latitude: 24.758214,
    longitude: 92.7911114,
    mapsUrl: 'https://maps.google.com/?q=24.758214,92.7911114',
    description: 'Mechanical Engineering workshop with manufacturing and fabrication labs.',
    isActive: true,
  },
  {
    slug: 'ece-cse-cc-building',
    name: 'ECE Dept, CSE Dept and CC Building',
    category: 'Academic Department',
    latitude: null,
    longitude: null,
    mapsUrl: 'https://maps.app.goo.gl/5hcBc5gstYdDBeEB9',
    description: 'Building housing Electronics & Communication Engineering, Computer Science Engineering departments and the Computer Centre.',
    isActive: true,
  },
  {
    slug: 'old-gallery',
    name: 'Old Gallery',
    category: 'Academic / Facility',
    latitude: null,
    longitude: null,
    mapsUrl: 'https://maps.app.goo.gl/P2F32WjjAx9uDRi98',
    description: 'Old Gallery – a gathering and exhibition space on campus.',
    isActive: true,
  },
]

async function main() {
  console.log('Seeding database...')

  // Seed Super Admin: 84agarwalharshit@gmail.com
  const passwordHash = await bcrypt.hash('campus@2024', 12)
  await prisma.adminUser.upsert({
    where: { email: '84agarwalharshit@gmail.com' },
    update: {
      role: 'SUPER_ADMIN',
    },
    create: {
      email: '84agarwalharshit@gmail.com',
      name: 'Harshit Agarwal',
      passwordHash,
      role: 'SUPER_ADMIN',
    },
  })
  console.log('Super Admin user created (email: 84agarwalharshit@gmail.com, password: campus@2024)')

  for (const loc of LOCATIONS) {
    await prisma.location.upsert({
      where: { slug: loc.slug },
      update: loc,
      create: loc,
    })
  }
  console.log(LOCATIONS.length + ' campus locations seeded')
  console.log('Database seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
